config/routes.rb
Rails.application.routes.draw do
  # Add ActionCable
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :listings do
    # collection do
    #   get :lookup
    # end
  end
  get '/price_lookup', to: 'listings#price_lookup'
  resources :users
  resources :categories
  resources :courses
  resources :personal_messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # get 'my-search-url', to: 'listings#search', as: 'my_search_url'

    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      post 'login', to: 'devise/sessions#create'
      delete 'logout', to: 'devise/sessions#destroy'
      get 'signup', to: 'devise/registrations#new'
    end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  validates :author, uniqueness: {scope: :receiver}
  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy
  has_many :users, through: :personal_messages

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  # Limit to one conversation between any two people
  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/views/conversations/_conversation.html.erb
<%= link_to conversation_path(conversation) do %>
  <%= small_gravatar_for(conversation.with(current_user), size: 30) %>
  <b><%= conversation.with(current_user).nickname %></b>
  <br>
  <em><%= conversation.personal_messages.last.body.truncate(50) %></em>
  <br>
  <hr>
<% end %>

app/views/conversations/index.html.erb
<h1 class="title">Conversations</h1>

<div id="conversations">
  <%= render @conversations if @conversations %>
</div>

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.erb
<%= link_to user_path(@conversation.with(current_user)) do %>
  <h1 class="title center">
    <%= small_gravatar_for(@conversation.with(current_user)) %> <%= @conversation.with(current_user).nickname %>
  </h1>
<% end %>

<div class="card" id="conversation-body" data-conversation-id="<%= @conversation.id %>">
  <div class="container">
      <%= render @conversation.personal_messages %>
  </div>

  <%= form_for @personal_message do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>
    <div class="form-group">
        <div class="col-sm-8 col-sm-offset-1">
          <%= f.text_area :body , rows:3, class: "form-control", placeholder: "Your Message..." %>
        </div>
        <div class="col-sm-3">
          <%= f.submit "Send", class: "btn btn-primary btn-md" %>
        </div>
      </div>
  <% end %>
</div>