config/routes.rb
Rails.application.routes.draw do
  # Add ActionCable
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :listings do
    # collection do
    #   get :lookup
    # end
  end
  get '/price_lookup', to: 'listings#price_lookup'
  resources :users
  resources :categories
  resources :courses
  resources :personal_messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # get 'my-search-url', to: 'listings#search', as: 'my_search_url'

    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      post 'login', to: 'devise/sessions#create'
      delete 'logout', to: 'devise/sessions#destroy'
      get 'signup', to: 'devise/registrations#new'
    end
end

app/models/user.rb
# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings, dependent: :destroy
  has_many :categories, through: :listings
  has_many :authored_conversations, class_name: 'Conversation',
           foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation',
           foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id
  before_save { self.email = email.downcase }
  VALID_UNC_EMAIL = /\A[\w+\-.]+@live.unc.edu\z/i
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_UNC_EMAIL, message:
                              'You must use a valid
                              @live.unc.edu email'
                            }
  current_year = Time.now.year
  validates :first_name, length: { maximum: 30 }
  validates :last_name, length: { maximum: 30 }
    # Optionals
    validates :summary, length: { maximum: 500 }, allow_nil: true
    validates :grad_year, numericality: { greater_than_or_equal_to: current_year,
                                          less_than_or_equal_to: current_year + 4,
                                          message: 'You must be graduating
                                          within the next 4 years' },
                                          allow_nil: true
# Assign nickname to user
  def nickname
    if first_name
      first_name
    elsif first_name && last_name
      first_name + ' ' + last_name
    elsif username
      username
    else
      email.split('@')[0]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy, :index]

    def index
      @users = User.paginate(page: params[:page], per_page: 15)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to Books #{@user.username}"
        redirect_to user_path(@user)
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      if @user.update(user_params)
        bypass_sign_in(@user)
        flash[:success] = 'Your account was updated successfully'
        redirect_to listings_path
      else
        render 'edit'
      end
    end

    def show
      @user_listings = @user.listings.paginate(page: params[:page], per_page: 5)
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:danger] = 'User and all articles created by user have been deleted.'
      redirect_to users_path
    end

    private
      def user_params
        params.require(:user).permit(:username, :email,
                                     :password, :first_name,
                                     :last_name, :summary,
                                     :grad_year
                                    )
      end

      def set_user
        @user = User.find(params[:id])
      end

      def require_same_user
        if (!user_signed_in? || current_user != @user) && !current_user.admin?
          flash[:danger] = "You can only edit your own profile"
          redirect_to user_path(@user)
        end
      end

      def require_admin
        if user_signed_in? and !current_user.admin?
          flash[:danger] = "Only admin users can perform that action."
          redirect_to courses_path
        end
      end


end

app/views/users/_listings.html.erb
<% @user.listings.reverse.each do |listing| %>
  <div class="col-md-6">
    <div class="card card-background" style="background-image: url(<%= listing.image.url %>)">
      <a href="#pablo"></a>
        <div class="card-content">
          <% listing.categories.each do |category| %>
          <li class="category-list">
            <%= link_to category_path(category), id: "category-label" do %>
              <span class="label label-primary"><%= category.name %></span>
            <% end %>
          </li>
        <% end %>
          <%= link_to listing_path(listing) do %>
          <h2 class="card-title"><%= truncate(listing.title, length: 20) %></h2>
          <% end %>
      </div>
    </div>
   </div>
<% end %>

app/views/users/_table.html.erb
<div class="table-responsive">
  <table class="table">
      <thead>
          <tr>
              <th>Title</th>
              <th class="text-right">Price</th>
              <th class="text-right">Actions</th>
          </tr>
      </thead>
      <tbody>
        <% @user.listings.each do |listing| %>
          <tr>
              <td><%= truncate(listing.title, length: 15) %></td>
              <td class="text-right">$ <%= listing.price %></td>
              <td class="td-actions text-right">
                <%= link_to edit_listing_path(listing) do %>
                  <button type="button" rel="tooltip" class="btn btn-success" data-original-title="" title="">
                      <i class="material-icons">edit</i>
                  </button>
                <% end %>
                <%= link_to listing_path(listing), method: :delete, data: {confirm: 'Are you sure you want to delete this listing?'} do %>
                  <button type="button" rel="tooltip" class="btn btn-danger" data-original-title="" title="">
                      <i class="material-icons">close</i>
                  </button>
                <% end %>
              </td>
          </tr>
<% end %>
      </tbody>
  </table>
  </div>

app/views/users/edit.html.erb
<h1 align="center">Edit account</h1>

<%= render "shared/errors", obj: @user %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <a href="https://en.gravatar.com" target="_blank"><h5>Change your profile picture</h5></a>
  </div>
</div>
<br />

<div class="container-fluid">
<div class="col-md-8 col-md-offset-2">
  <div class="card">
    <div class="header header-raised header-primary text-center">
        <h4 class="card-title">Edit Profile</h4>
    </div>
    <%= form_for(@user, :html => {class: "form-horizontal" , role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username , class: "form-control" , placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email  %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email , class: "form-control", placeholder: "Enter email", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :first_name  %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :first_name , class: "form-control", placeholder: "First Name (optional, but recommended)", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :last_name  %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :last_name , class: "form-control", placeholder: "Last Name (optional, but recommended)", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :summary  %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :summary ,rows: 8, class: "form-control", placeholder: "Tell sellers a little bit about you (optional)", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :grad_year  %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :grad_year, class: "form-control", placeholder: "Graduation Year (optional)", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password  %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password , class: "form-control", placeholder: "Enter old password or create a new one", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <%= f.submit "Update", class: "btn btn-primary btn-lg" %>
          </div>
      </div>
    <%end%>
  </div>
</div>
</div>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<br \>
<div class="container">
  <% @users.each_slice(3) do |user_row| %>
      <div class="row">
        <% user_row.each do |user| %>
        <div class="col-md-4">
          <div class="card card-profile">
            <div class="card-avatar">
                <%= link_to gravatar_for(user), user_path(user) %>
            </div>

            <div class="card-content">
              <h6 class="category text-gray"><%= user.username %></h6>

              <h4 class="card-title"><%= user.first_name + " " + user.last_name if user.first_name && user.last_name %></h4>

              <% if user.summary %>
              <p class="card-description">
                <%= user.summary %>
              </p>
              <% end %>
              <% if user_signed_in? && current_user.admin? %>
                <li class="center"><%= link_to "Delete this user", user_path(user), method: :delete,
                         data: { confirm: "Are you sure you want to delete the user and all articles?" } %></li>
              <% end %>
              <a href="#pablo" class="btn btn-info btn-round">Follow</a>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
</div>

<%= will_paginate @users, align: 'center' %>

app/views/users/new.html.erb
<h1 align="center">Sign up for Books</h1>

<%= render "shared/errors", obj: @user %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal" , role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :username , class: "form-control" , placeholder: "Enter username", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email , class: "form-control", placeholder: "Enter email", autofocus: true %>

      </div>
      </div>
      <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password  %>
      </div>
      <div class="col-sm-8">
        <%= f.password_field :password , class: "form-control", placeholder: "Enter password", autofocus: true %>
      </div>
      </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit "Sign up", class: "btn btn-primary btn-lg" %>
        </div>
    </div>
  <%end%>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :body_class, "profile-page" %>

<div class="page-header header-filter" data-parallax="true" filter-color="primary-solid"></div>
	<div class="main main-raised">
		<div class="profile-content">
            <div class="container">
                <div class="row">
	                <div class="col-xs-6 col-xs-offset-3">
        	           <div class="profile">
	                        <div class="avatar">
	                            <%= gravatar_for @user, size: 150, class: "img-circle img-responsive img-raised" %>
	                        </div>
	                        <div class="name">
	                            <h3 class="title"><%= @user.first_name + " " + @user.last_name if @user.first_name && @user.last_name%></h3>
															<% if current_user == @user %>
															<a href="https://en.gravatar.com" target="_blank">Change your profile picture</a>
															<% end %>
															<% if @user.grad_year %>
																<h6>Graduates in <%= @user.grad_year %></h6>
															<% end %>
	                        </div>
	                    </div>
    	            </div>
									<!--
                    <div class="col-xs-2 follow">
	                   <button class="btn btn-fab btn-primary" rel="tooltip" title="Follow this user">
                            <i class="material-icons">add</i>
                        </button>
	                	</div>
									-->
                </div>
								<% if @user.listings.count > 0 %>
                <div class="description text-center">
									<% if @user.summary %>
										<p><%= @user.summary %></p>
									<% end %>
									<% if current_user != @user %>
											<%= link_to new_personal_message_path(receiver_id: @user) do %>
												<button class="btn btn-primary">Message <%= @user.nickname %></button>
											<% end %>
										<% end %>
                </div>


				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<div class="profile-tabs">
		                    <div class="nav-align-center">
								<ul class="nav nav-pills nav-pills-icons" role="tablist">
									<li class="active">
                    <a href="#work" role="tab" data-toggle="tab">
											<i class="material-icons">reorder</i>
											Listings (<%= @user.listings.count %>)
                    </a>
			             </li>
			           </ul>
							</div>
						</div>
						<!-- End Profile Tabs -->
					</div>
        </div>
                <div class="tab-content">
			        		<div class="tab-pane active work" id="work">
				        		<div class="row">
	                   	<div class="col-md-7 col-md-offset-1">
		                  	<h4 class="title">Latest Listings</h4>
		                     	<div class="row collections">
														<%= render 'listings' %>
                            </div>
		                    	</div>

		                  <div class="col-md-2 col-md-offset-1 stats">
			                    <h4 class="title">Stats</h4>
			                    <ul class="list-unstyled">
				                    <li><b><%= @user.listings.count %></b> <%= "Book".pluralize(@user.listings.count) %></li>
				                    <li><b><%= @user.categories.distinct.count %></b> <%= "Subject".pluralize(@user.categories.distinct.count) %></li>
				                    <!-- <li><b>1.2K</b> Likes</li> -->
				                	</ul>
				                	<hr />
												<% if @user.categories.count > 0 %>
													<h4 class="title">Subjects</h4>
													<% @user.categories.distinct.each do |category| %>
													<li class="category-list">
														<%= link_to category_path(category), id: "category-label" do %>
															<span class="label label-primary"><%= category.name %></span>
														<% end %>
													</li>
												<% end %>
												<hr>
												<% end %>
												<% if (current_user == @user || current_user.admin?) && current_user.listings.count > 0 %>
												<h4 class="title">Edit/Delete Postings</h4>
												<%= render 'table' %>
												<% end %>
			                </div>
	                 </div>
			        	</div>
			    		</div>
							<% else %>
							<div class="container no-listings">
								<h5 class="center">Currently no listings.
									<% if @user == current_user %>
										<%= link_to new_listing_path do %>
												Click here to add a book.
										<% end %>
									<% end %>
								</h5>
							</div>
							<% end %>

            </div>
        	</div>
				</div>