config/routes.rb
Rails.application.routes.draw do
  # Add ActionCable
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :listings do
    # collection do
    #   get :lookup
    # end
  end
  get '/price_lookup', to: 'listings#price_lookup'
  resources :users
  resources :categories
  resources :courses
  resources :personal_messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # get 'my-search-url', to: 'listings#search', as: 'my_search_url'

    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      post 'login', to: 'devise/sessions#create'
      delete 'logout', to: 'devise/sessions#destroy'
      get 'signup', to: 'devise/registrations#new'
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :listing_categories
  has_many :course_categories
  has_many :courses, through: :course_categories
  has_many :listings, through: :listing_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 60 }
  validates :shortname, length: { minimum: 1, maximum: 8 }
  validates_uniqueness_of :name
  validates_uniqueness_of :shortname
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:destroy]
  def index
    @categories = Category.paginate(page: params[:page], per_page: 15)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
    flash[:success] = 'Category was created successfully'
    redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_listings = @category.listings.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category.destroy
    flash[:danger] = 'Category was successfully deleted'
    redirect_to categories_path
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category successfully updated.'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

private
  def category_params
    params.require(:category).permit(:name, :shortname, course_ids: [])
  end

  def require_admin
    if !user_signed_in? || (user_signed_in? and !current_user.admin?)
      flash[:danger] = 'Only admins can perform that action'
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/views/categories/_card.html.erb
<% @category_listings.each_slice(3) do |list_row| %>
<div class="row">
    <% list_row.each do |listing| %>
    <div class="col-md-4">
    <div class="card card-profile card-plain">
      <a href="<%= listing_path(listing) %>">
        <div class="card-image">
          <img class="img" src="<%= listing.image.url %>">
          <div class="card-title">
            $ <%= listing.price %>
          </div>
          <div style="background-image: url(<%= listing.image.card.url %>); opacity: 1;"></div>
          <div class="ripple-container"></div>
      </div>
      </a>
    <a href="<%= listing_path(listing) %>">
      <div class="card-content">
        <h6 class="category text-default"><%= truncate(listing.title, length: 30) %></h6>

        <div class="footer">
          <div class="col-md-6">
            <%= link_to user_path(listing.user) do %>
              <div class="author">
                  <%= small_gravatar_for listing.user, class: "img-circle img-responsive img-raised", align: "left" %>
                     <span><%= show_full_name(listing) %></span>
              </div>
              <% end %>
            </div>
            <div class="col-md-6">
              <p class="card-description">
                <%= listing.condition %>
              </p>
          </div>
        </div>
      </div>
    </a>

    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/categories/_category.html.erb
<%= link_to category_path(category), id: "category-label" do %>
  <span class="label label-primary"><%= category.name %></span>
<% end %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>
      <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
        <%= f.label :shortname %>
      </div>
      <div class="col-sm-8">
          <%= f.text_field :shortname, class: "form-control", placeholder: "Shortname (ex: MATH, ECON, etc.)", autofocus: true %>
      </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/categories/_listing-categories.html.erb
<div class="col-md-8 col-md-offset-2">
      <div class="table-responsive">
      <table class="table">
          <thead>
              <tr>
                  <th>Name</th>
                  <th class="text-right"># of Listings</th>
                  <th class="text-right">Actions</th>
              </tr>
          </thead>
          <tbody>
            <% obj.each do |category| %>
              <tr>
                  <td><%= link_to "#{category.name}", category_path(category) %></td>
                  <td class="text-right"><%= category.listings.count %></td>
                  <td class="td-actions text-right">
                    <a href="<%= category_path(category) %>">
                      <button type="button" rel="tooltip" class="btn btn-primary" data-original-title="" title="">
                          <i class="material-icons">list</i>
                      </button>
                    </a>
                      <% if user_signed_in? && (current_user.admin?) %>
                        <a href="<%= edit_category_path(category) %>"
                          <button type="button" rel="tooltip" class="btn btn-success" data-original-title="" title="">
                              <i class="material-icons">edit</i>
                          </button>
                        </a>
                        <%= link_to category_path(category), method: :delete, data: {confirm: 'Are you sure you want to delete this category?'} do %>
                          <button type="button" rel="tooltip" class="btn btn-danger" data-original-title="" title="">
                              <i class="material-icons">close</i>
                          </button>
                        <% end %>
                      <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
      </table>
      </div>
    </div>

app/views/categories/_listing.html.erb
<div class="col-md-8 col-md-offset-2">
      <div class="table-responsive">
      <table class="table">
          <thead>
              <tr>
                  <th>Title</th>
                  <th>Condition</th>
                  <th class="text-right">Price</th>
                  <th class="text-right">Actions</th>
              </tr>
          </thead>
          <tbody>
            <% @category_listings.each do |listing| %>
              <tr>
                  <td><%= truncate(listing.title, length: 30) %></td>
                  <td><%= listing.condition %></td>
                  <td class="text-right">$ <%= listing.price %></td>
                  <td class="td-actions text-right">
                    <a href="<%= listing_path(listing) %>">
                      <button type="button" rel="tooltip" class="btn btn-primary" data-original-title="" title="">
                          <i class="material-icons">list</i>
                      </button>
                    </a>
                      <% if current_user == listing.user || current_user.admin? %>
                        <a href="<%= edit_listing_path(listing) %>"
                          <button type="button" rel="tooltip" class="btn btn-success" data-original-title="" title="">
                              <i class="material-icons">edit</i>
                          </button>
                        </a>
                        <%= link_to listing_path(listing), method: :delete, data: {confirm: 'Are you sure you want to delete this listing?'} do %>
                          <button type="button" rel="tooltip" class="btn btn-danger" data-original-title="" title="">
                              <i class="material-icons">close</i>
                          </button>
                        <% end %>
                      <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
      </table>
      </div>
    </div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Departments</h1>
<br \>
<div class="container">
<%= render 'listing-categories', obj: @categories %>
</div>
    <% if current_user.admin? %>
    <br \>
      <div align="center">
        <%= link_to "New Department", new_category_path, class: "btn btn-primary"%>
      </div>
    <% end %>
    <div class="center">
      <%= will_paginate @categories %>
    </div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name.capitalize + " Department" %></h1>
<div align="center">
<% if user_signed_in? && current_user.admin? %>
  <div class="row">
    <span class="label label-default"><%= link_to "Edit category name", edit_category_path(@category) %></span>
  </div>
<% end %>
  <%= will_paginate @category_listings %>
</div>
 <%= render 'card' %>
 <div align="center">
  <%= will_paginate @category_listings %>
</div>