config/routes.rb
Rails.application.routes.draw do
  # Add ActionCable
  mount ActionCable.server => '/cable'

  devise_for :users
  resources :listings do
    # collection do
    #   get :lookup
    # end
  end
  get '/price_lookup', to: 'listings#price_lookup'
  resources :users
  resources :categories
  resources :courses
  resources :personal_messages, only: [:create, :new]
  resources :conversations, only: [:index, :show]
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # get 'my-search-url', to: 'listings#search', as: 'my_search_url'

    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      post 'login', to: 'devise/sessions#create'
      delete 'logout', to: 'devise/sessions#destroy'
      get 'signup', to: 'devise/registrations#new'
    end
end

app/views/layouts/_base.html.erb
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>

    <title>List Overflow</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <%= favicon_link_tag 'apple-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
    <%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= yield :head %>
  </head>
  <body class="<%= yield :class %>" data-features="<%= yield :features %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
    <div class="row">
			<div class="col-md-4">
	  			<h6 class="moody-ventures">&copy; Moody Ventures, LLC</h6>
			</div>
			<div class="col-md-4">
         <ul class="pull-center">
          <li><%= link_to "Terms", terms_path %></li>
          <li><%= link_to "Privacy", privacy_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
			</div>
				<div class="col-md-4">
					<ul class="pull-center">
          <li><%= link_to "https://www.facebook.com/List-Overflow-512717969077443/", class: "btn btn-just-icon btn-simple", target: "_blank" do %><i class="fa fa-facebook"></i><% end %></li>
          <li><%= link_to "https://www.instagram.com/listoverflow", class: "btn btn-just-icon btn-simple", target: "_blank" do %><i class="fa fa-instagram"></i><% end %></li>
          <li><%= link_to "https://twitter.com/list_overflow", class: "btn btn-just-icon btn-simple", target: "_blank" do %><i class="fa fa-twitter"></i><% end %></li>
        </ul>
			</div>
    </div>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<div class="row message-space">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%>'>
        <div class="alert-icon">
  						<i class="material-icons">
                <% if name == "success" %>
                  check
                <% elsif name == "info" %>
                  info_outline
                <% elsif name == "danger" %>
                  error_outline
                <% elsif name == "alert" %>
                <% elsif name == "warning" %>
                  warning
                <% end %>
              </i>
  					</div>
      <a href="#" class = "close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <%end%>
  </div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
  <% if content_for?(:nav_transparent) %>
    <nav class="navbar navbar-fixed-top navbar-inverse navbar-transparent navbar-color-on-scroll"
         color-on-scroll = "" id="sectionsNav">
  <% else %>
    <nav class = "navbar navbar-fixed-top navbar-inverse" id="sectionsNav" >
  <% end %>
    	<div class="container">
        	<!-- Brand and toggle get grouped for better mobile display -->
        	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
            		<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
        		</button>
        		<a class="navbar-brand" href="<%= root_path %>"><%= image_tag("ListOverflowLogo.svg", size: '128') %><div class="ripple-container"></div></a>
        	</div>

        	<div class="collapse navbar-collapse" id="example-navbar-primary">
        		<ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                 <li>
                   <%= link_to courses_path do %>
					         <i class="material-icons">school</i>Courses
				           <% end %>
    				      </li>
            <% if current_user.admin? %>
    				<li class="dropdown">
    					<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    						<i class="material-icons">add</i> Actions
    						<b class="caret"></b>
    					<div class="ripple-container"></div></a>
    					<ul class="dropdown-menu dropdown-with-icons">
                <li><%= link_to "Post Book", new_listing_path %></li>
                <li><%= link_to "New Category", new_category_path %></li>
                <li><%= link_to "New Course", new_course_path %></li>
    					</ul>
    				</li>
            <% else %>
            <li><%= link_to new_listing_path do %><i class="material-icons">add</i>Post Book<% end %></li>
            <% end %>
            <% end %>

            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i><%= "(Admin)" if current_user.admin? %><%= "Profile" if !current_user.admin? %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Messages", conversations_path %></li>
                  <li><%= link_to "View profile", user_path(current_user) %></li>
                  <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: :delete %></li>
                </ul>
              </li>
              <li class="dropdown" data-behavior='notifications'>
                <a href="#" class="btn btn-primary btn-raised" data-toggle='dropdown' role="button" aria-haspopup="true" aria-expanded="false" data-behavior='notifications-link'>
                  <i class="material-icons">notifications</i><span data-behavior='unread-count'></span>
                </a>
                <ul class="dropdown-menu" data-behavior='notification-items' id='notifications-ul'>

                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path, class: "btn btn-default btn-raised btn-round" %></li>
            <% end %>

        		</ul>

        	</div>
    	</div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>List Overflow</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'shortcut icon', type: 'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-93563702-5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-93563702-5');
    </script>
  </head>

    <% if content_for?(:body_class) %>
    <body class="<%= yield (:body_class) %>">
    <% end %>
    <% if !content_for?(:nav_transparent) %>
      <%= render 'layouts/navigation' %>
      <div class="section-space"></div>
    <% else %>
      <%= render 'layouts/navigation' %>
    <% end %>

    <% if !content_for?(:body_class) %>
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>

    <%= render 'layouts/footer' %>
  </body>
</html>